apiVersion: batch/v1
kind: Job
metadata:
  name: model-download-job
  namespace: ai-inference-cpu-demo
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: redhat-registry-pull
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
      containers:
        - name: model-download
          image: registry.redhat.io/rhaii/vllm-cpu-rhel9:3.5.0-1786546771
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              umask 022
              hf download Qwen/Qwen2.5-1.5B-Instruct --local-dir /models/Qwen2.5-1.5B-Instruct
          env:
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
                  optional: true
          volumeMounts:
            - name: model-cache
              mountPath: /models
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
