apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-inference-cache
  namespace: ai-inference-cpu-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
