apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen25-instruct
  namespace: ai-inference-cpu-demo
  annotations:
    openshift.io/display-name: "Qwen 2.5 1.5B Instruct (CPU)"
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cpu-x86-runtime
      storageUri: "pvc://ai-inference-cache/Qwen2.5-1.5B-Instruct"
      resources:
        requests:
          cpu: "4"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 16Gi
